description: >
    Volans inventory fixups

events:
    - name: Add Chassis interface
      description: >
          Add the chassis interface on the chassis inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/board/Volans_Motherboard:
                  xyz.openbmc_project.Inventory.Item: